### ISSUE TITLE
SHA 1 contact no firebases authentication error

### ISSUE THREAD

**Issue by data-pirate-pwl** [data-pirate-pwl/LanjewarTutorial#1]
![20200402_005138](https://user-images.githubusercontent.com/61533257/78177721-2c867f00-747c-11ea-914f-9259c74a62c6.jpg)

I m trying to verify contact no by otp using firebase while testing it shows me some error regarding SHA 1 . i managed that time by finding sha1 key n uploading on firebase settings. But after relesing signed apk i get same issue..

**Comment by subhamkr555** [comment]
On it.
